Repository kubernetes-client/gen, pull requests merged in 2018-08, with the labels that each got.

#72 Add custom object status and scale api
  openapi/custom_objects_spec.json
  openapi/preprocess_spec.py
Labels: cncf-cla: yes, size/XL

#73 fix two responses which were in the wrong level
  openapi/custom_objects_spec.json
Labels: cncf-cla: yes, size/XS

#74 Fix proto generation.
  proto/dependencies.sh
  proto/generate.sh
  proto/install.sh
Labels: cncf-cla: yes, size/XS

#77 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, size/S

#78 Add OWNERS file
  OWNERS
Labels: cncf-cla: yes, size/XS
