Repository kubernetes-client/gen, pull requests merged in 2019-07, with the labels that each got.

#119 feat: custom objects can be merged by json-patch
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 update node version for autorest
  openapi/csharp.xml
  openapi/swagger-codegen/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#123 Bugfix: Preserve field manager types for java client
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#122 Skip fetching swagger from upstream using `OPENAPI_SKIP_FETCH_SPEC` env
  openapi/openapi-generator/client-generator.sh
  openapi/preprocess_spec.py
  openapi/swagger-codegen/client-generator.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#124 Revert "preserve field manager types (#123)"
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Switch typescript client to use openapi-generator
  openapi/typescript.sh
  openapi/typescript.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#126 Correct typescript library to use standard spelling on CRD property JSONPath
  openapi/typescript.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS
