Repository kubernetes-client/gen, pull requests merged in 2019-03, with the labels that each got.

#108 haskell client: switch to openapi-generator
  openapi/haskell-http-client.xml
  openapi/haskell.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#106 feat: add fieldSelector to list/watch methods in custom objects spec
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#107 [Ruby] Fix parameter name
  openapi/ruby.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Switch ruby client to use openapi-generator
  openapi/ruby.sh
  openapi/ruby.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Various changes to the haskell client
  openapi/haskell-http-client.xml
  openapi/haskell.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#112 add remove_models (specific to client languages) in process_swagger
  openapi/haskell-http-client.xml
  openapi/haskell.sh
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 Add perl client generator scripts and configuration
  openapi/perl.sh
  openapi/perl.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#110 Switch golang to openapi-generator.
  openapi/go.sh
  openapi/go.xml
Labels: approved, cncf-cla: yes, lgtm, size/S
