Repository kubernetes-client/gen, pull requests merged in 2019-11, with the labels that each got.

#134 Fixes the wrong link auto-generation in the python generator
  openapi/python.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#117 Chore: Migrate java clients from swagger-codegen to openapi-generator
  openapi/java.sh
  openapi/java.xml
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#136 feat: python-asyncio with all variants generated by openapi-generator
  openapi/python-asyncio.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#137 Remove Javascript. They're not used.
  openapi/javascript.sh
  openapi/javascript.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#138 Remove swagger-codegen from the repo.
  openapi/csharp.sh
  openapi/swagger-codegen/Dockerfile
  openapi/swagger-codegen/client-generator.sh
  openapi/swagger-codegen/generate_client_in_container.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#139 Disable reflective deep equal
  openapi/java.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS
