Repository kubernetes-client/gen, pull requests merged in 2019-01, with the labels that each got.

#94 Add timeoutSeconds to CustomObjectsApi list/watch calls
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#95 feat: introduce openapi-generator
  openapi/csharp.sh
  openapi/go.sh
  openapi/haskell.sh
  openapi/java.sh
  openapi/javascript.sh
  openapi/openapi-generator/Dockerfile
  openapi/openapi-generator/client-generator.sh
  openapi/openapi-generator/generate_client_in_container.sh
  openapi/python-asyncio-api_client.py.patch
  openapi/python-asyncio-rest.py.patch
  openapi/python-asyncio.sh
  openapi/python-asyncio.xml
  openapi/python.sh
  openapi/ruby.sh
  openapi/swagger-codegen/Dockerfile
  openapi/swagger-codegen/client-generator.sh
  openapi/swagger-codegen/generate_client_in_container.sh
  openapi/typescript.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#96 feat: add x-codegen-request-body-name in preprocessing step
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/XS
