Repository kubernetes-client/gen, pull requests merged in 2020-05, with the labels that each got.

#155 Correct operationId on DELETE collection operations for custom objects
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#154 Adding dry-run & fieldmanagers to custom specs
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#157 Bugfix: Revert delete operation name updates
  openapi/custom_objects_spec.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Remove watch/allowWatchBookmarks from deleteCollection openapi parameters
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#160 Add typescript-jquery generator
  openapi/typescript-jquery.sh
  openapi/typescript-jquery.xml
Labels: approved, cncf-cla: yes, lgtm, size/M
