Repository kubernetes-client/gen, pull requests merged in 2020-06, with the labels that each got.

#161 ad-hoc client generation for CRDs
  openapi/java.xml
  openapi/openapi-generator/client-generator.sh
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#162 Adding scripts for java CRD model generation
  openapi/java-crd-cmd.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#163 Fixes CRD preprocess aborting
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Bump code-gen and applies x-implements extension
  openapi/java.sh
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#166 Fixes crd model generation aborting on missing ListMeta
  openapi/java-crd-cmd.sh
  openapi/openapi-generator/client-generator.sh
  openapi/preprocess_spec.py
Labels: approved, cncf-cla: yes, lgtm, size/S
