Repository kubernetes-client/gen, pull requests merged in 2021-11, with the labels that each got.

#210 Convert a number of XML files to generatorName
  openapi/go.xml
  openapi/perl.xml
  openapi/python-asyncio.xml
  openapi/ruby.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#211 Update proto generation.
  proto/dependencies.sh
  proto/generate.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#213 Update typescript open API generator to handle the IntOrString type
  openapi/preprocess_spec.py
  openapi/typescript.xml
Labels: cncf-cla: yes, size/S, approved, lgtm
