Repository kubernetes-client/gen, pull requests merged in 2023-12, with the labels that each got.

#257 Allow customize USE_SINGLE_PARAMETER for Java generator
  openapi/java.xml
  openapi/openapi-generator/client-generator.sh
  openapi/openapi-generator/generate_client_in_container.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#256 feat: Add label selector for deletion api of custom object collection
  openapi/custom_objects_spec.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#258 Fix kubernetes object assumption
  openapi/preprocess_spec.py
Labels: cncf-cla: yes, size/XS, approved, lgtm

#261 fix: unbound variable USE_SINGLE_PARAMETER
  openapi/openapi-generator/client-generator.sh
  openapi/openapi-generator/generate_client_in_container.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#262 chore: bump maven to 3.9.6
  openapi/openapi-generator/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#260 Add fieldValidation to custom objects API
  openapi/custom_objects_spec.json
Labels: cncf-cla: yes, size/M, approved, lgtm
