Repository kubernetes-client/gen, pull requests merged in 2023-08, with the labels that each got.

#247 Issue 246 Update java.sh
  openapi/java.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#248 fix Mismatched URLs in client side
  openapi/preprocess_spec.py
Labels: cncf-cla: yes, size/S, approved, lgtm

#249 Issues-246 - Added attributes for generated pom.xml
  openapi/java.xml
  openapi/openapi-generator/client-generator.sh
  openapi/openapi-generator/generate_client_in_container.sh
Labels: cncf-cla: yes, size/M, approved, lgtm
